// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Miv.Data;

namespace Miv.Migrations
{
    [DbContext(typeof(MivContext))]
    partial class MivContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Miv.Models.Attaching", b =>
                {
                    b.Property<int>("AttachingID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContentID");

                    b.Property<int>("MaterialID");

                    b.HasKey("AttachingID");

                    b.HasIndex("ContentID");

                    b.HasIndex("MaterialID");

                    b.ToTable("Attachings");
                });

            modelBuilder.Entity("Miv.Models.Content", b =>
                {
                    b.Property<int>("ContentID");

                    b.Property<string>("Description");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("Name");

                    b.HasKey("ContentID");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Miv.Models.Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("imgUrl");

                    b.HasKey("ID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Miv.Models.Attaching", b =>
                {
                    b.HasOne("Miv.Models.Content", "Content")
                        .WithMany("Attachings")
                        .HasForeignKey("ContentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Miv.Models.Material", "Material")
                        .WithMany("Attachings")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
